using System.Text;
using System.Text.Json;

namespace BinlogMcp.Visualization;

/// <summary>
/// Generates bar charts for performance data (slowest items, comparisons).
/// </summary>
public static class BarChart
{
    /// <summary>
    /// Generates an HTML page with a bar chart visualization.
    /// </summary>
    public static string Generate(BarChartData data)
    {
        var body = new StringBuilder();

        // Header
        body.AppendLine($"<h1>{HtmlTemplate.EscapeHtml(data.Title)}</h1>");
        body.AppendLine($"<p class=\"subtitle\">{data.Items.Count} items</p>");

        if (data.Comparison != null)
        {
            // Comparison mode - show before/after
            body.AppendLine(GenerateComparisonContent(data));
        }
        else
        {
            // Single chart mode
            body.AppendLine(GenerateSingleChartContent(data));
        }

        // Footer
        body.AppendLine("<div class=\"footer\">Generated by BinlogMcp Visualization</div>");

        var script = data.Comparison != null
            ? GenerateComparisonScript(data)
            : GenerateSingleChartScript(data);

        return HtmlTemplate.WrapInHtmlPage(data.Title, body.ToString(), script);
    }

    private static string GenerateSingleChartContent(BarChartData data)
    {
        var sb = new StringBuilder();

        // Stats
        var total = data.Items.Sum(i => i.Value);
        var top5 = data.Items.Take(5).Sum(i => i.Value);
        var top5Pct = total > 0 ? (top5 / total) * 100 : 0;

        sb.AppendLine("<div class=\"stats-grid\">");
        sb.AppendLine(HtmlTemplate.StatCard("Total", HtmlTemplate.FormatDuration(total)));
        sb.AppendLine(HtmlTemplate.StatCard("Items", data.Items.Count.ToString()));
        sb.AppendLine(HtmlTemplate.StatCard("Top 5", $"{top5Pct:F0}%"));
        sb.AppendLine(HtmlTemplate.StatCard("Slowest", HtmlTemplate.FormatDuration(data.Items.FirstOrDefault()?.Value ?? 0)));
        sb.AppendLine("</div>");

        // Chart
        sb.AppendLine("<div class=\"chart-container\">");
        sb.AppendLine($"<h2 class=\"chart-title\">{HtmlTemplate.EscapeHtml(data.YAxisLabel)}</h2>");
        sb.AppendLine("<canvas id=\"barChart\"></canvas>");
        sb.AppendLine("</div>");

        // Table
        sb.AppendLine("<div class=\"chart-container\">");
        sb.AppendLine("<h2 class=\"chart-title\">Details</h2>");
        sb.AppendLine(GenerateTable(data));
        sb.AppendLine("</div>");

        return sb.ToString();
    }

    private static string GenerateComparisonContent(BarChartData data)
    {
        var sb = new StringBuilder();
        var comparison = data.Comparison!;

        // Calculate summary stats
        var baselineTotal = comparison.Items.Sum(i => i.BaselineValue);
        var currentTotal = comparison.Items.Sum(i => i.CurrentValue);
        var delta = currentTotal - baselineTotal;
        var deltaPct = baselineTotal > 0 ? (delta / baselineTotal) * 100 : 0;

        var slower = comparison.Items.Count(i => i.CurrentValue > i.BaselineValue * 1.05);
        var faster = comparison.Items.Count(i => i.CurrentValue < i.BaselineValue * 0.95);

        sb.AppendLine("<div class=\"stats-grid\">");
        sb.AppendLine(HtmlTemplate.StatCard(comparison.BaselineLabel, HtmlTemplate.FormatDuration(baselineTotal)));
        sb.AppendLine(HtmlTemplate.StatCard(comparison.CurrentLabel, HtmlTemplate.FormatDuration(currentTotal)));
        sb.AppendLine(HtmlTemplate.StatCard("Delta", $"{(delta >= 0 ? "+" : "")}{deltaPct:F1}%", delta > 0 ? "warning" : delta < 0 ? "" : null));
        sb.AppendLine(HtmlTemplate.StatCard("Slower", slower.ToString(), slower > 0 ? "warning" : null));
        sb.AppendLine(HtmlTemplate.StatCard("Faster", faster.ToString(), faster > 0 ? "" : null));
        sb.AppendLine("</div>");

        // Comparison chart
        sb.AppendLine("<div class=\"chart-container\">");
        sb.AppendLine("<h2 class=\"chart-title\">Performance Comparison</h2>");
        sb.AppendLine("<canvas id=\"comparisonChart\"></canvas>");
        sb.AppendLine("<div class=\"legend\">");
        sb.AppendLine(HtmlTemplate.LegendItem(comparison.BaselineLabel, "#4dc9f6"));
        sb.AppendLine(HtmlTemplate.LegendItem(comparison.CurrentLabel, "#f67019"));
        sb.AppendLine("</div>");
        sb.AppendLine("</div>");

        // Delta chart (regressions/improvements)
        sb.AppendLine("<div class=\"chart-container\">");
        sb.AppendLine("<h2 class=\"chart-title\">Changes (Sorted by Impact)</h2>");
        sb.AppendLine("<canvas id=\"deltaChart\"></canvas>");
        sb.AppendLine("</div>");

        // Table
        sb.AppendLine("<div class=\"chart-container\">");
        sb.AppendLine("<h2 class=\"chart-title\">Details</h2>");
        sb.AppendLine(GenerateComparisonTable(comparison));
        sb.AppendLine("</div>");

        return sb.ToString();
    }

    private static string GenerateTable(BarChartData data)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<table>");
        sb.AppendLine($"<thead><tr><th>{HtmlTemplate.EscapeHtml(data.XAxisLabel)}</th><th>{HtmlTemplate.EscapeHtml(data.YAxisLabel)}</th><th>% of Total</th></tr></thead>");
        sb.AppendLine("<tbody>");

        var total = data.Items.Sum(i => i.Value);

        foreach (var item in data.Items.Take(30))
        {
            var pct = total > 0 ? (item.Value / total) * 100 : 0;
            sb.AppendLine($"""
                <tr>
                    <td>{HtmlTemplate.EscapeHtml(item.Label)}</td>
                    <td class="duration">{HtmlTemplate.FormatDuration(item.Value)}</td>
                    <td>{pct:F1}%</td>
                </tr>
                """);
        }

        sb.AppendLine("</tbody></table>");
        return sb.ToString();
    }

    private static string GenerateComparisonTable(BarChartComparison comparison)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<table>");
        sb.AppendLine($"<thead><tr><th>Item</th><th>{HtmlTemplate.EscapeHtml(comparison.BaselineLabel)}</th><th>{HtmlTemplate.EscapeHtml(comparison.CurrentLabel)}</th><th>Delta</th><th>Change</th></tr></thead>");
        sb.AppendLine("<tbody>");

        var sorted = comparison.Items
            .OrderByDescending(i => Math.Abs(i.Delta))
            .Take(30);

        foreach (var item in sorted)
        {
            var changeTag = item.DeltaPercent switch
            {
                > 5 => "<span class=\"tag tag-slower\">Slower</span>",
                < -5 => "<span class=\"tag tag-faster\">Faster</span>",
                _ => "<span class=\"tag\">~Same</span>"
            };

            var deltaStr = item.Delta >= 0
                ? $"+{HtmlTemplate.FormatDuration(item.Delta)}"
                : $"-{HtmlTemplate.FormatDuration(-item.Delta)}";

            sb.AppendLine($"""
                <tr>
                    <td>{HtmlTemplate.EscapeHtml(item.Label)}</td>
                    <td class="duration">{HtmlTemplate.FormatDuration(item.BaselineValue)}</td>
                    <td class="duration">{HtmlTemplate.FormatDuration(item.CurrentValue)}</td>
                    <td class="duration">{deltaStr}</td>
                    <td>{changeTag}</td>
                </tr>
                """);
        }

        sb.AppendLine("</tbody></table>");
        return sb.ToString();
    }

    private static string GenerateSingleChartScript(BarChartData data)
    {
        var items = data.Items.Take(20).ToList();
        var labelsJson = JsonSerializer.Serialize(items.Select(i => TruncateLabel(i.Label)).ToArray());
        var valuesJson = JsonSerializer.Serialize(items.Select(i => i.Value).ToArray());
        var colorsJson = JsonSerializer.Serialize(items.Select((i, idx) => i.Color ?? HtmlTemplate.GetColor(idx)).ToArray());

        return $$"""
            <script>
            document.addEventListener('DOMContentLoaded', function() {
                const labels = {{labelsJson}};
                const values = {{valuesJson}};
                const colors = {{colorsJson}};

                const ctx = document.getElementById('barChart').getContext('2d');

                new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: labels,
                        datasets: [{
                            label: '{{HtmlTemplate.EscapeHtml(data.YAxisLabel)}}',
                            data: values,
                            backgroundColor: colors,
                            borderColor: colors,
                            borderWidth: 1
                        }]
                    },
                    options: {
                        indexAxis: 'y',
                        responsive: true,
                        plugins: {
                            legend: { display: false },
                            tooltip: {
                                callbacks: {
                                    label: function(context) {
                                        return formatDuration(context.raw);
                                    }
                                }
                            }
                        },
                        scales: {
                            x: {
                                title: { display: true, text: 'Duration (ms)', color: '#888' },
                                grid: { color: '#2a2a4a' },
                                ticks: { color: '#888' }
                            },
                            y: {
                                grid: { display: false },
                                ticks: { color: '#ccc' }
                            }
                        }
                    }
                });
            });

            function formatDuration(ms) {
                if (ms < 1000) return ms.toFixed(0) + 'ms';
                if (ms < 60000) return (ms / 1000).toFixed(1) + 's';
                return (ms / 60000).toFixed(1) + 'm';
            }
            </script>
            """;
    }

    private static string GenerateComparisonScript(BarChartData data)
    {
        var comparison = data.Comparison!;
        var items = comparison.Items.Take(15).ToList();
        var labelsJson = JsonSerializer.Serialize(items.Select(i => TruncateLabel(i.Label)).ToArray());
        var baselineJson = JsonSerializer.Serialize(items.Select(i => i.BaselineValue).ToArray());
        var currentJson = JsonSerializer.Serialize(items.Select(i => i.CurrentValue).ToArray());

        // Delta chart data - sorted by absolute delta
        var deltaItems = comparison.Items
            .OrderByDescending(i => Math.Abs(i.Delta))
            .Take(15)
            .ToList();
        var deltaLabelsJson = JsonSerializer.Serialize(deltaItems.Select(i => TruncateLabel(i.Label)).ToArray());
        var deltaValuesJson = JsonSerializer.Serialize(deltaItems.Select(i => i.Delta).ToArray());
        var deltaColorsJson = JsonSerializer.Serialize(deltaItems.Select(i => i.Delta > 0 ? "#f55" : "#0a5").ToArray());

        return $$"""
            <script>
            document.addEventListener('DOMContentLoaded', function() {
                // Comparison chart
                const compLabels = {{labelsJson}};
                const baseline = {{baselineJson}};
                const current = {{currentJson}};

                const compCtx = document.getElementById('comparisonChart').getContext('2d');
                new Chart(compCtx, {
                    type: 'bar',
                    data: {
                        labels: compLabels,
                        datasets: [
                            {
                                label: '{{HtmlTemplate.EscapeHtml(comparison.BaselineLabel)}}',
                                data: baseline,
                                backgroundColor: '#4dc9f6',
                                borderColor: '#4dc9f6',
                                borderWidth: 1
                            },
                            {
                                label: '{{HtmlTemplate.EscapeHtml(comparison.CurrentLabel)}}',
                                data: current,
                                backgroundColor: '#f67019',
                                borderColor: '#f67019',
                                borderWidth: 1
                            }
                        ]
                    },
                    options: {
                        indexAxis: 'y',
                        responsive: true,
                        plugins: {
                            legend: { display: false },
                            tooltip: {
                                callbacks: {
                                    label: function(context) {
                                        return context.dataset.label + ': ' + formatDuration(context.raw);
                                    }
                                }
                            }
                        },
                        scales: {
                            x: {
                                title: { display: true, text: 'Duration (ms)', color: '#888' },
                                grid: { color: '#2a2a4a' },
                                ticks: { color: '#888' }
                            },
                            y: {
                                grid: { display: false },
                                ticks: { color: '#ccc' }
                            }
                        }
                    }
                });

                // Delta chart
                const deltaLabels = {{deltaLabelsJson}};
                const deltaValues = {{deltaValuesJson}};
                const deltaColors = {{deltaColorsJson}};

                const deltaCtx = document.getElementById('deltaChart').getContext('2d');
                new Chart(deltaCtx, {
                    type: 'bar',
                    data: {
                        labels: deltaLabels,
                        datasets: [{
                            label: 'Change',
                            data: deltaValues,
                            backgroundColor: deltaColors,
                            borderColor: deltaColors,
                            borderWidth: 1
                        }]
                    },
                    options: {
                        indexAxis: 'y',
                        responsive: true,
                        plugins: {
                            legend: { display: false },
                            tooltip: {
                                callbacks: {
                                    label: function(context) {
                                        const v = context.raw;
                                        const sign = v >= 0 ? '+' : '';
                                        return sign + formatDuration(v) + (v > 0 ? ' slower' : ' faster');
                                    }
                                }
                            }
                        },
                        scales: {
                            x: {
                                title: { display: true, text: 'Delta (ms)', color: '#888' },
                                grid: { color: '#2a2a4a' },
                                ticks: { color: '#888' }
                            },
                            y: {
                                grid: { display: false },
                                ticks: { color: '#ccc' }
                            }
                        }
                    }
                });
            });

            function formatDuration(ms) {
                const abs = Math.abs(ms);
                if (abs < 1000) return ms.toFixed(0) + 'ms';
                if (abs < 60000) return (ms / 1000).toFixed(1) + 's';
                return (ms / 60000).toFixed(1) + 'm';
            }
            </script>
            """;
    }

    private static string TruncateLabel(string label)
    {
        const int maxLen = 35;
        if (label.Length <= maxLen) return label;
        return label[..(maxLen - 3)] + "...";
    }
}
