using System.Text;
using System.Text.Json;

namespace BinlogMcp.Visualization;

/// <summary>
/// Generates a Gantt-style timeline chart showing parallel build execution.
/// </summary>
public static class TimelineChart
{
    /// <summary>
    /// Generates an HTML page with a timeline visualization.
    /// </summary>
    public static string Generate(TimelineData data)
    {
        var buildDuration = (data.BuildEnd - data.BuildStart).TotalMilliseconds;
        var stats = CalculateStats(data);

        var body = new StringBuilder();

        // Header
        body.AppendLine($"<h1>{HtmlTemplate.EscapeHtml(data.Title)}</h1>");
        body.AppendLine($"<p class=\"subtitle\">Build Duration: {HtmlTemplate.FormatDuration(buildDuration)} | {data.Rows.Count} items</p>");

        // Stats cards
        body.AppendLine("<div class=\"stats-grid\">");
        body.AppendLine(HtmlTemplate.StatCard("Total Duration", HtmlTemplate.FormatDuration(buildDuration)));
        body.AppendLine(HtmlTemplate.StatCard("Projects", stats.ProjectCount.ToString()));
        body.AppendLine(HtmlTemplate.StatCard("Targets", stats.TargetCount.ToString()));
        body.AppendLine(HtmlTemplate.StatCard("Max Parallelism", stats.MaxParallelism.ToString()));
        body.AppendLine(HtmlTemplate.StatCard("Avg Parallelism", stats.AvgParallelism.ToString("F1")));
        body.AppendLine("</div>");

        // Timeline chart
        body.AppendLine("<div class=\"chart-container\">");
        body.AppendLine("<h2 class=\"chart-title\">Build Timeline</h2>");
        body.AppendLine("<canvas id=\"timelineChart\"></canvas>");
        body.AppendLine("<div class=\"legend\">");
        body.AppendLine(HtmlTemplate.LegendItem("Project", HtmlTemplate.GetCategoryColor("project")));
        body.AppendLine(HtmlTemplate.LegendItem("Target", HtmlTemplate.GetCategoryColor("target")));
        body.AppendLine(HtmlTemplate.LegendItem("Task", HtmlTemplate.GetCategoryColor("task")));
        body.AppendLine("</div>");
        body.AppendLine("</div>");

        // Top items table
        body.AppendLine("<div class=\"chart-container\">");
        body.AppendLine("<h2 class=\"chart-title\">Slowest Items</h2>");
        body.AppendLine(GenerateSlowestTable(data));
        body.AppendLine("</div>");

        // Footer
        body.AppendLine("<div class=\"footer\">Generated by BinlogMcp Visualization</div>");

        // Chart script
        var script = GenerateTimelineScript(data);

        return HtmlTemplate.WrapInHtmlPage(data.Title, body.ToString(), script);
    }

    private static string GenerateSlowestTable(TimelineData data)
    {
        var slowest = data.Rows
            .Select(r => new { Row = r, Duration = (r.End - r.Start).TotalMilliseconds })
            .OrderByDescending(x => x.Duration)
            .Take(20)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("<table>");
        sb.AppendLine("<thead><tr><th>Item</th><th>Category</th><th>Duration</th><th>Status</th></tr></thead>");
        sb.AppendLine("<tbody>");

        foreach (var item in slowest)
        {
            var statusTag = item.Row.Status switch
            {
                "failed" or "failure" => "<span class=\"tag tag-failed\">Failed</span>",
                "skipped" => "<span class=\"tag tag-skipped\">Skipped</span>",
                _ => "<span class=\"tag tag-success\">Success</span>"
            };

            sb.AppendLine($"""
                <tr>
                    <td>{HtmlTemplate.EscapeHtml(item.Row.Label)}</td>
                    <td>{HtmlTemplate.EscapeHtml(item.Row.Category)}</td>
                    <td class="duration">{HtmlTemplate.FormatDuration(item.Duration)}</td>
                    <td>{statusTag}</td>
                </tr>
                """);
        }

        sb.AppendLine("</tbody></table>");
        return sb.ToString();
    }

    private static string GenerateTimelineScript(TimelineData data)
    {
        // Convert data to Chart.js format
        // We'll use a horizontal bar chart to simulate a Gantt chart
        var chartData = data.Rows
            .OrderBy(r => r.Start)
            .Take(50) // Limit for performance
            .Select((r, i) => new
            {
                label = TruncateLabel(r.Label),
                start = (r.Start - data.BuildStart).TotalMilliseconds,
                end = (r.End - data.BuildStart).TotalMilliseconds,
                duration = (r.End - r.Start).TotalMilliseconds,
                category = r.Category,
                color = HtmlTemplate.GetCategoryColor(r.Category),
                status = r.Status ?? "success"
            })
            .ToList();

        var labelsJson = JsonSerializer.Serialize(chartData.Select(d => d.label).ToArray());
        var dataJson = JsonSerializer.Serialize(chartData.Select(d => new[] { d.start, d.end }).ToArray());
        var colorsJson = JsonSerializer.Serialize(chartData.Select(d => d.color).ToArray());
        var durationsJson = JsonSerializer.Serialize(chartData.Select(d => d.duration).ToArray());

        return $$"""
            <script>
            document.addEventListener('DOMContentLoaded', function() {
                const labels = {{labelsJson}};
                const timeRanges = {{dataJson}};
                const colors = {{colorsJson}};
                const durations = {{durationsJson}};

                const ctx = document.getElementById('timelineChart').getContext('2d');

                new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: labels,
                        datasets: [{
                            label: 'Duration',
                            data: timeRanges.map((range, i) => ({
                                x: [range[0], range[1]],
                                y: labels[i]
                            })),
                            backgroundColor: colors,
                            borderColor: colors.map(c => c),
                            borderWidth: 1,
                            borderSkipped: false,
                            barPercentage: 0.8
                        }]
                    },
                    options: {
                        indexAxis: 'y',
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: { display: false },
                            tooltip: {
                                callbacks: {
                                    label: function(context) {
                                        const idx = context.dataIndex;
                                        const dur = durations[idx];
                                        const start = timeRanges[idx][0];
                                        return [
                                            'Duration: ' + formatDuration(dur),
                                            'Start: ' + formatDuration(start)
                                        ];
                                    }
                                }
                            }
                        },
                        scales: {
                            x: {
                                type: 'linear',
                                position: 'top',
                                title: { display: true, text: 'Time (ms)', color: '#888' },
                                grid: { color: '#2a2a4a' },
                                ticks: { color: '#888' }
                            },
                            y: {
                                grid: { display: false },
                                ticks: { color: '#ccc', font: { size: 11 } }
                            }
                        }
                    }
                });

                // Set canvas height based on data
                document.getElementById('timelineChart').parentElement.style.height =
                    Math.max(400, labels.length * 25 + 100) + 'px';
            });

            function formatDuration(ms) {
                if (ms < 1000) return ms.toFixed(0) + 'ms';
                if (ms < 60000) return (ms / 1000).toFixed(1) + 's';
                return (ms / 60000).toFixed(1) + 'm';
            }
            </script>
            """;
    }

    private static string TruncateLabel(string label)
    {
        const int maxLen = 40;
        if (label.Length <= maxLen) return label;
        return label[..(maxLen - 3)] + "...";
    }

    private record TimelineStats(int ProjectCount, int TargetCount, int TaskCount, int MaxParallelism, double AvgParallelism);

    private static TimelineStats CalculateStats(TimelineData data)
    {
        var projectCount = data.Rows.Count(r => r.Category.Equals("project", StringComparison.OrdinalIgnoreCase));
        var targetCount = data.Rows.Count(r => r.Category.Equals("target", StringComparison.OrdinalIgnoreCase));
        var taskCount = data.Rows.Count(r => r.Category.Equals("task", StringComparison.OrdinalIgnoreCase));

        // Calculate parallelism at different time points
        var events = new List<(DateTime Time, int Delta)>();
        foreach (var row in data.Rows)
        {
            events.Add((row.Start, 1));
            events.Add((row.End, -1));
        }

        int current = 0, max = 0;
        double totalWeighted = 0;
        var sortedEvents = events.OrderBy(e => e.Time).ThenByDescending(e => e.Delta).ToList();
        DateTime? lastTime = null;

        foreach (var evt in sortedEvents)
        {
            if (lastTime.HasValue && current > 0)
            {
                totalWeighted += current * (evt.Time - lastTime.Value).TotalMilliseconds;
            }
            current += evt.Delta;
            max = Math.Max(max, current);
            lastTime = evt.Time;
        }

        var buildDuration = (data.BuildEnd - data.BuildStart).TotalMilliseconds;
        var avgParallelism = buildDuration > 0 ? totalWeighted / buildDuration : 0;

        return new TimelineStats(projectCount, targetCount, taskCount, max, avgParallelism);
    }
}
